package Crypto_Tool;

public class most_Frequency {
	public static void main(String[]args) {
		
		String s=
				" GVDPU ODTDL MFDME MMUSX MDWRD GAEEZ AUSZB LETAO"
				+ " LDARA WAUEZ AUSZH QCKAU RETUB NDCPK OFRNQ PNMCS"
				+ " OBASN IDMBP OAUZK PUBFT MTFXX FTDNM NVUNF ILDFE"
				+ " TRKAH QARES RVRQD MFXTA SRNHI BQRPR GQUZA ELDVB"
				+ " AKFAM ITUQP CUAEA CQNKW LDHSD QRTFS RAAYT ACWLD"
				+ " BSACM CARBQ TRAET DABAK AQKLR KHQRN CRAUH DADAS"
				+ " BEMTT RCTBK SZGVH QCULD NRANM DNMKC UDANU AYEHD"
				+ " SEMRI SUHXF PDLDH SCTLK XNPKM FNHIB QRPRG TQKAT"
				+ " LDHQR KBIRU TSBEM TTRCT BKSZG VHQRK ESHQS RODAD"
				+ " LDFSM USNQP LBKRR IWSWR SVLSD LKWRU HUDXA ETSRQ"
				+ " DMDMH QATRE AWART SMUHQ ARESS GFARV OACTQ TUSTM"
				+ " HAQTT ASUQP MZRUL DFAZX SXGVH QRCBV RQTGR NDPDL"
				+ " TRESR QDMLD VBAKF AUVCT UAWRS VTDDO NHHQT UINBK"
				+ " RSURK XSTCN XNQAC TVBDM FSRAE YAECK QNTAN RMUKS"
				+ " MQKAT GOEDN RTVRA TDOCU AETCD NTARV OFTHA KTMUA"
				+ " WFCTK OAETR EAARF AMISE PKSNA URTRE AWARR ENZMQ"
				+ " EYAES KEFWC RVOAT HCTBK SZFTX NXAAW RONZD TRERL"
				+ " MAFAO RESSG FTRIA WAUTR MQKSN RMUFB CKLQD QOATA"
				+ " TRRFP KTGRU HTTAS EFBRW AEZMH QAEHN SDNHR EFAGY"
				+ " DTAQA SDVMF HQCKQ RMSKB FTAKH UXNPK MAHQT DYELD"
				+ " HQRCF XQAMT RSERT FDEPK MFNSE HFTEH TDWCL SEIUN"
				+ " FILDL DRPUR HQCKS TAQAT REFAC SNMTA AZAQL DPGHT"
				+ " BVATH TUQQT INDMT ULNBL KCETQ THQPD TAXLL DBQTE"
				+ " NZDOF TDVMF SLLSE AOAPX HQDNH BHQRC ARESW SUDUA"
				+ " DVHEP DGVEA WRFXL DHBPR RNRBA TTSMD HQAEZ UNMUR"
				+ " OBPDT AXLLD EFFLT UMUSN ATREA WARFA UBXFP DRUHU"
				+ " SYAUT SRQDM STFAV BRXKB RQOSF TSODT DLMFL DBQTM"
				+ " LNBLK CCSUA ESPAV BUADV PNEFE ARNWG DONSM UAELD"
				+ " FBKRH NHACT IBQRP RBGDT KCRPD LEAXF MUHUM AVRAE"
				+ " RUBQT MQSQD MAHQR KESFT MRREE KLETA WREAF IUZHQ"
				+ " RKDLR QFXFE XNPAE MFYCS TRRUN SVGAC LBSZN HBLKC"
				+ " ETURR NDPFB SAKFN QPKMA MRENN RBKDN GYXFM AFTNR"
				+ " LYLSE AOAPX LDBKU AESRA ORCTA URQEA IBQRP RBQOA"
				+ " AKPKC SUFAU ARZUE IUNTR ZCAUQ RGPBV KYSTF KMTLD"
				+ " BSDNM UBQNY ";

		System.out.println(s.replace(" ", ""));
		
	}
}
